### ISSUE TITLE
Crash report seems to point to this mod.

### ISSUE THREAD

**Issue by Artellia** [Tfarcenim/EnchantmentControl#1]
Running this mod and u team core only and I get the attached error report. 
[crash-2020-04-12_20.21.46-client.txt](https://github.com/Tfarcenim/EnchantmentControl/files/4467601/crash-2020-04-12_20.21.46-client.txt)
u team core alone does not cause the error. I tried Forge version 31.1.12, 31.1.30, and 31.1.44 all with an error.

**Comment by Tfarcenim** [comment]
add the missing dependency https://www.curseforge.com/minecraft/mc-mods/extra-tags
