### ISSUE TITLE
[1.15.2] Crash when used with a mod that use the LootFunctionManager

### ISSUE THREAD

**Issue by HyCraftHD** [Tfarcenim/EnchantmentControl#2]
I got a report yesterday of an incompatibility with your mod.

https://github.com/MC-U-Team/U-Team-Core/issues/37

The issue is that it cannot find this field when loading the transformed EnchantRandomly class: 
https://github.com/Tfarcenim/EnchantmentControl/blob/266bf1379a66c4776fe82d75edbf8260fc92aba7/src/main/java/tfar/enchantmentcontrol/mixin/EnchantRandomlyMixin.java#L28

The class is loaded by the static register of LootFunctionManager when a mod tries to register a loot table function like here:
https://github.com/MC-U-Team/U-Team-Core/blob/77a79c5d9cb2b18594ded23233e56cdf3987927e/src/main/java/info/u_team/u_team_core/intern/init/UCoreLootTableRegistry.java#L17

It seems to be a problem that the mapped field name is not in the refmap json but I'm not really into mixin.

The crashlog is here: https://github.com/MC-U-Team/U-Team-Core/files/4472675/latest.log

Tested it in a dev environment and it worked.

Furthermore it would be nice to add the dependencies in your mods.toml file so it does not crash randomly but generates better error message that users can easily understand.

**Comment by crdtrd** [comment]
I think I got the same problem in my modpack. Here's my crash report: 
[crash-2020-04-27_02.35.37-client.txt](https://github.com/Tfarcenim/EnchantmentControl/files/4538834/crash-2020-04-27_02.35.37-client.txt)
